apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-ingress
  namespace: default
spec:
  dnsNames:
    - aditya.ddns.net
  secretName: nginx-wordpress-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
