apiVersion: v1
kind: Secret
metadata:
  name: wp-db-secrets
  namespace: default
type: Opaque
data:
  # This is base64 encoded -- the real password is NGiJi6A46YJTjTx
  MYSQL_ROOT_PASSWORD: TkdpSmk2QTQ2WUpUalR4
